### ISSUE TITLE
discord上でアルバムのタイトル（taisho）を投稿されたら、taishoアルバムの画像を一枚表示する

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#12]

**Comment by marukaz** [comment]
GetAlbumUrls関数使ってください

**Comment by hitohunt** [comment]
discord側の標準入力機能がわからないので、取り急ぎ既知のalbum名入力時の表示にします。

**Comment by marukaz** [comment]
標準入力機能って？

**Comment by hitohunt** [comment]
> 標準入力機能って？
入力側（チャット側）で
!indicate
>taisho
>ピクチャ表示
みたいな形で実装してみるといいのかなと思ったけど、それの方法がわからないっていうカンジです。

**Comment by marukaz** [comment]
ああ、たしかにそれは説明しておいたほうがよかったかも
前に調べたんだけどdiscordで画像を表示するには単に `ChannelMessageSend()` の contentをURLにすればいいっぽい

つまり、流れとしては

taishoって投稿される→GetAlbumUrlsを使って画像のURLを手に入れる→ `s.ChannelMessageSend(m.ChannelID, 手に入れたURL)` を実行

でいけるはず

参考: https://discord.com/developers/docs/resources/channel#create-message

**Comment by hitohunt** [comment]
画像表示方法についてではありません。チャット側で標準入力を受け取る口を用意できるかどうかといった主旨です。
これからの拡張性を考えたときに表示用のコマンド（!Indicateなど）を用意して、入力受け取る口があればアルバム名を入力、そのあと表示出来たらいいと思ったのでさきのリプライです。

とりあえず、taishoで表示するというところをゴールとします。

**Comment by marukaz** [comment]
おお、そこまで考えてくれてたんですね
とりあえずこのissueはtaishoで表示するのがゴールのつもりだったのでそれでいいと思います！
コマンドについてはけっこう大事な部分なので、明日みんなでどういうUIにするか話し合えるといいかもしれないですね
