### ISSUE TITLE
Discord botの申請とトークンの共有

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#2]

**Comment by marukaz** [comment]
権限はとりあえず適当につけてたりなかったら増やす

**Comment by hitohunt** [comment]
![DiscordBot権限一覧](https://user-images.githubusercontent.com/33319869/131251062-a3cc10de-ed06-45bc-b2f5-c73a8bfb437f.png)

権限一覧を参考までにうｐしておきます。
取り急ぎはSend Messageの権限はマストかもしれません。
