### ISSUE TITLE
アルバム表示UIの実装

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#22]
!albumでアルバムのリストと、対応する番号をリアクションで表示し、番号をクリックされたらそのアルバムの画像を表示する

**Comment by marukaz** [comment]
コマンドスタイルの場合：

```
まるまる — 今日 21:17
!album
```

```
albumbot ボット — 今日 21:17
1. taisho
2. oemori
1️⃣  2️⃣ 
```

→ 1️⃣ をクリックする
→ botがtaishoアルバムの画像を表示してくれる

**Comment by tah1git** [comment]
bot招待時に「アルバム一覧」と「アルバム申請」のチャンネルを作成
・アルバム一覧
albumbotが持っているアルバムをメッセージごとに投稿されているチャンネル

・（アルバム申請）
タイトルを送信すると空のアルバムを作成する

アルバムに画像を登録するのはどのチャンネルからでも可能

アルバムを見る場合は、
・アルバム一覧チャンネルを見る
・!album タイトルでアルバムを表示させる

アルバムのリストを見る場合
・!albumlistでアルバムのリストを表示
　→https://github.com/Among-Angels/albumbot/issues/22#issuecomment-939474031

**Comment by tah1git** [comment]
すべてのアルバムのタイトルを取得する関数が欲しい

**Comment by marukaz** [comment]
#36
