### ISSUE TITLE
.envの書き方

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#3]

**Comment by hitohunt** [comment]
DISCORD_TOKEN=**YOURTOKEN** という形で記載すればとりあえずdotenv上は動きました。
格納場所は現状はmain.goと同じディレクトリ([project/cmd/albumbot/](https://github.com/Among-Angels/albumbot/tree/main/cmd/albumbot))ですね。
後々、CLIENT_IDやVOICE_CHANNEL_IDといったDiscord特有のIDは別途必要になるかもしれません。
