### ISSUE TITLE
botの応答速度の改善

### ISSUE THREAD

**Issue by tah1git** [Among-Angels/albumbot#35]

**Comment by hitohunt** [comment]
応答速度が遅い挙動事項まとめ
・4,5件画像が表示された後に画像取得が止まる。
・リアクションされる挙動が遅い。

**Comment by marukaz** [comment]
画像に関しては今 @hitohunt が #68 でやってくれてる

**Comment by marukaz** [comment]
アルバム名の表示時も同じ問題が起きてる、おそらくdiscordの連投制限？bot側で一つの文字列にまとめてAPI叩くのを一回だけにすれば解決できそう

**Comment by tah1git** [comment]
応答速度の改善確認したんでクローズします
