### ISSUE TITLE
任意のリアクションに反応してしまうバグの修正

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#43]
## バグの説明

任意のメッセージにリアクションがつくとbotが反応してアルバムの一覧を表示したあとメッセージを削除してしまう

**Comment by marukaz** [comment]
## プルリクエストのやり方

1. commitをpushする
2. github上のこのリポジトリに飛ぶとプルリクエストを作るみたいな表示があるので押す

https://atmarkit.itmedia.co.jp/ait/articles/1702/27/news022.html

**Comment by tah1git** [comment]
onReactionAdd内でメッセージの削除対象を「番号を選んでね！」に絞れていないことが原因
条件がbot以外がリアクションをしたとき

https://github.com/Among-Angels/albumbot/blob/5c05438b42fbf30f5f5dd4129a7740bf5f4a426b/bot.go#L180-L207
