### ISSUE TITLE
!album helpコマンドの実装

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#50]
!album helpコマンドで機能の一覧が表示されてほしい

**Comment by marukaz** [comment]
コマンドラインだとflagライブラリで勝手にhelpを生成したりできるが、我々のbotで同じことができるかは不明 https://qiita.com/Yaruki00/items/7edc04720a24e71abfa2

愚直に文章をベタ書きしてもいいと思う

**Comment by hitohunt** [comment]
#52
