### ISSUE TITLE
vscodeの設定共有

### ISSUE THREAD

**Issue by hitohunt** [Among-Angels/albumbot#6]
Setting Syncってプロジェクト向けに使えるものですかね。
各人の好みとかvim使いたいとかありそうですけど。
[https://code.visualstudio.com/docs/editor/settings-sync](https://code.visualstudio.com/docs/editor/settings-sync)

**Comment by marukaz** [comment]
Settings Syncはひとつのアカウントが異なるPC間で同じ設定を使えるようにするもの（たとえば僕は会社のMacと自分のWindowsのvscodeの設定をSettings Syncで同期してる）だからちょっと違うかな

**Comment by hitohunt** [comment]
無知晒しただけだった・・・クローズしときます！

**Comment by marukaz** [comment]
issue自体は正当なものだから使わせていただきます！！
