### ISSUE TITLE
albumaddおよびalbumcreate時エラー

### ISSUE THREAD

**Issue by hitohunt** [Among-Angels/albumbot#62]
最新のコードをgit pullして動かしたら、以下のようなエラーが出たのでDynamoDBのテーブル名を指定したという前座があります。
`panic: TABLE_NAMEを指定してください。(-TABLE_NAME=<VALUE>)`

その後実行エラーは解消されました。しかし、標記のとおりコマンドを試験用の自鯖のbotに打ち込むと以下のようなエラーが出ました。
`Got an error scanning the table:
operation error DynamoDB: Scan, https response error StatusCode: 400, RequestID: BU9V6H6G556T4RTJS5RLTDQ6FRVV4KQNSO5AEMVJF66Q9ASUAAJG, api error ValidationException: 2 validation errors detected: Value '' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+; Value '' at 'tableName' failed to satisfy constraint: Member must have length greater than or equal to 3`

tableNameが何か言われてるので、設定ミスってるかもしれないが原因がわかれば教えてください。

**Comment by marukaz** [comment]
`var table = aws.String("Albums")` に戻しても以下のエラーが出る

Got an error scanning the table:
operation error DynamoDB: Scan, https response error StatusCode: 400, RequestID: E7LRSNMVV045O0I5LGU8UL8B3FVV4KQNSO5AEMVJF66Q9ASUAAJG, ResourceNotFoundException: Requested resource not foun
