### ISSUE TITLE
アルバムの画像表示をページ送りにする

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#68]
これを使うことになると思う

https://github.com/Among-Angels/albumbot/blob/b6517062bbdcfa8ce87da683ef7f98e7766ba8fc/album.go#L88

**Comment by hitohunt** [comment]
5枚ごとに表示を考えています。
現状悩んでいる点としては以下になります。

- →スタンプを押したあとにすでに表示した画像を削除するかどうか。
削除しないとなると結局遷移するのにもログが縦長になるので、削除したい。ただ削除するとなると5枚分メッセージを削除することになるが、その方法が現状不明。

コメントをもらった上の関数について、今の処理だと数字スタンプが押された時点であるタイトルのurls全体のリストを拾ってくるので、部分的にその関数を呼ぶっていうよりかは、すでに拾ったリストからインデックスを指定ってことになりそうなので使う場面あるのかなという感じです。

**Comment by marukaz** [comment]
会話メモ

- メッセージの編集でもできそう
  - 一個の投稿にまとめられると編集しやすくなりそう
  - 編集に使うメソッドはたぶんこれ https://pkg.go.dev/github.com/bwmarrin/discordgo@v0.23.2?utm_source=gopls#Session.ChannelMessageEdit
  - messageIDをどう取得する？ -> リアクションと同じやつにすれば紐付けられそう

**Comment by marukaz** [comment]
`GetAlbumPage()` を使うと毎回DBを叩いてしまうので実装変えたほうがいいかも？

**Comment by hitohunt** [comment]
#82
