### ISSUE TITLE
アルバムを削除できるようにする

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#85]

**Comment by marukaz** [comment]
これ使う https://github.com/Among-Angels/albumbot/blob/4722fc93e2a0a82925edfb115e5aa011c8fd081c/album.go#L169

**Comment by hitohunt** [comment]
@marukaz  コマンドで!delete(重複させないなら!eliminate？とか) titlenameってするのか、!albumみたいな感じで一覧表示からスタンプ押して、削除するようにするのか今迷ってます。

**Comment by hitohunt** [comment]
#89
