### ISSUE TITLE
アルバムの名前を変えられるようにする

### ISSUE THREAD

**Issue by marukaz** [Among-Angels/albumbot#86]

**Comment by keyamin** [comment]
現状DynamoDBのパーティションキーをタイトルにしてるんだけど、パーティションキーに指定されてる値を変更することが出来ないから、テーブル設計変えないとだめかも

**Comment by marukaz** [comment]
それかアルバムの画像の一覧を取得して、削除して新しい名前でアルバム作成して全部追加するかだね。設計変えられるならその方がいいだろうけど

**Comment by keyamin** [comment]
一旦新規作成+削除で実装します！
